### PR TITLE
Fixing git apply --index for gvfs

### PR DESCRIPTION
**Pull request by turbonaitis**
This addresses the GVFS issue, documented here: 
https://github.com/Microsoft/VFSForGit/issues/809

### CODE REVIEW

**Comment by kewillford** [comment]
Because we want to get to the point of not having custom code in git for GVFS, you should try `apply --index` using a sparse checkout repo to see if the problem repros without have GVFS in the picture since GVFS is using the same mechanism as sparse checkout.  If it does then try to create some tests for it in the git tests and fix it for sparse checkout which might also fix it for GVFS.  Then we could upstream the change to git core and not have a bunch of custom code that will be difficult to maintain moving forward.

**Comment by benpeart** [comment]
Kevin beat me to it but I'll post my anyway. :)

From a quick look, I don't think this bug is specific to GVFS but is a bug in git with how it deals with index entries with the skip-worktree bit set.  When skip-worktree is set, git doesn't update the stat data in the index for that cache entry so they could be all zero as you describe.

I believe you could reproduce this with any version of git by configuring sparse-checkout to exclude files that are in the patch you attempt to apply with '--index.'  The fix should be a patch in core git to have it pay attention to the skip-worktree bit (rather than a patch specific to the gvfs flag/fork).

**Comment by benpeart** [comment]
BTW - thanks for finding this issue and letting us know.  I just realized that this bug is also going to exist for the rarely used 'assume-unchanged' feature.  The fix should check both ce_uptodate(ce) and ce_skip_worktree(ce) when recognizing that the cache entry data will be invalid/ignored.

If you are not familiar with submitting patches to the git mailing list let me know, I'm happy to lend a hand.  A test script that demonstrates the problem and subsequent fix typically makes getting it accepted easier.

**Comment by turbonaitis** [comment]
I think the situation with sparse-checkout is different. If sparse checkout excludes a file, it's not just missing data in the index, it also does not exist on disk, so the lstat call will return an error and we'll end up in a different execution path.  And in that case, patch is applied successfully. 

Of course, if we manually create the file, that is excluded from sparse-checkout, and then try to patch it - then it fails, but I would say that's somewhat expected (as the file is essentially untracked at that point, right?) 

Now, this is all different in GVFS case - the file is there (lstat succeeds), it's not untracked and we're trying to patch it - but it still fails. I'm open to exploring other solutions, than the one proposed in this PR, but I don't think this is related to sparse-checkouts.

**Comment by kewillford** [comment]
>Of course, if we manually create the file, that is excluded from sparse-checkout, and then try to patch it - then it fails, but I would say that's somewhat expected (as the file is essentially untracked at that point, right?)

This is the exact case for GVFS. With GVFS, git will not start tracking the file until it is written to so the skip-worktree bit will be on and there will not be any lstat data in the index when the file has only been read but it is in the working directory.  So in the sparse checkout case, maybe it should apply and not fail if the file that is there matches the sha in the index when the skip-worktree bit is set.

I will think about this more though and see if I can come up with some other ideas to handle this.

**Comment by turbonaitis** [comment]
From purely git's perspective, I agree, that it's the same case, but looking holistically - with GVFS, I'm just operating normally and try to apply a patch - completely normal workflow, which has to work (either git ignores stat info, while in a virtualized repo, or we add in some hook, that downloads the file, before patching, hydrates it, lets git index it and only then does all these checks). 

While with sparse checkout, it's completely different - first of all, who would manually create a file, that's outside the sparse-checkout list and then try to patch it? And of course, the error is completely justified, as the file that was created is not in the index and we've no way of telling whether it has anything in common with the actual file in the repository.

**Comment by turbonaitis** [comment]
So, where do we go with this? You guys still think, that this should be addressed in the context of sparse checkout, where the scenario would be, that:
1. I setup sparse checkout to exclude some file
2. I manually add that file to the working directory (god knows from where) 
3. I then try to patch that file with explicit `--index` option, which asks git to add the patched file to index (which I don't think even makes sense in a sparse checkout case) 

The scenario above doesn't seem to make sense to me from a vanilla git standpoint and I don't see how the maintainers would merge a change addressing it.

**Comment by turbonaitis** [comment]
Reverted my previous changes, as it turned out they broke `git status` and perhaps others as well. 

This now looks generic enough to submit to upstream.

**Comment by kewillford** [comment]
How long has this change been in there?  Did the commit comments help better understand why this was in there in the first place?  I will build a version for VFSForGit and run it through our tests.  Thanks!

**Comment by turbonaitis** [comment]
This has been introduced by this: https://github.com/Microsoft/git/commit/56cac48c3550de88d71b3944576d44337261d71b

which seems to be addressing an issue, not related in any way to this execution path and is simply replacing one flag with two OR'ed flags everywhere.

**Comment by kewillford** [comment]
Yeah I see what you mean.  It would be good to get some tests in the git code to demonstrate the issue and that this will fix it.  Did you run the git tests against this change?  Looks like there might be some tests failing because of it?

**Comment by turbonaitis** [comment]
All the existing tests pass (except one, which also fails on the latest
version of vfs-2.20.1). I'll try to add test and reproduce the bug later.

**Comment by derrickstolee** [comment]
Closing due to inactivity. Please reactivate if you plan to work on this more.

**Comment by turbonaitis** [comment]
It's fine, if I understand correctly, we're not merging PRs to this fork anyway, but rather submit patches to upstream directly.

**Pull request closed without merging**
