### PR TITLE
scalar: set core.fsync=all for stability

### PR DESCRIPTION
**Pull request by derrickstolee**
The core.fsync config option was introduced in b9f5d0358d2 (core.fsync: documentation and user-friendly aggregate options, 2022-03-15), and first shipped in Git 2.36.0. This config option allows customizing which layers of Git data require fsync().

One issue is that 020406eaa52 (core.fsync: introduce granular fsync control infrastructure, 2022-03-10) changed the default behavior of fsync()ing index files (among others) such that users are starting to see issues where their .idx files are empty, halting their interactions with their repositories.

Setting core.fsync=all will use fsync() in all possible places, avoiding this issue in any data written by Git. Here, we are preferring stability over performance. This is left as an optional setting so users can override with their preferred setting, if needed. At that point, they accept the risk of not fsync()ing.

* [X] This is an early version of work ~~already under review~~ to consider for upstream contribution.

---

This is something that is affecting users right now, specifically when using the GVFS protocol. The precomputed prefetch packs are getting empty `.idx` files pretty frequently. This is very likely an `fsync()` issue, but the frequency is still alarming.

### CODE REVIEW

**Comment by dscho** [comment]
I wonder whether `scalar` is the best layer for this.

An alternative would be to include `FSYNC_COMPONENT_PACK` and `FSYNC_COMPONENT_INDEX` in [`FSYNC_COMPONENTS_DEFAULT`](https://github.com/microsoft/git/commit/b9f5d0358d2e882d47f496c1a5589f6cebc25578#diff-acb4a9eb70f6768f379c18fe3dca2893f0b9028ae51261008e5520a58f37e625R1016-R1018).

**Comment by derrickstolee** [comment]
> e `FSYNC_COMPONENT_PACK` and `FSYNC_COMPONENT_INDEX`

`FSYNC_COMPONENT_PACK` is already enabled by `FSYNC_COMPONENTS_OBJECTS`, so maybe we should add `FSYNC_COMPONENT_INDEX` to `FSYNC_COMPONENTS_OBJECTS`.

**Comment by derrickstolee** [comment]
> `FSYNC_COMPONENT_INDEX`

Actually, `FSYNC_COMPONENT_INDEX` is for the `.git/index` file. Instead, `FSYNC_COMPONENT_PACK_METADATA` is used for pack-indexes. That bit seems to be on for `FSYNC_COMPONENTS_DEFAULT`.

I wonder if the `gvfs-helper` process doesn't load these bits at all. I'll start looking into that.

**Comment by derrickstolee** [comment]
> I wonder if the `gvfs-helper` process doesn't load these bits at all. I'll start looking into that.

This doesn't seem to be the problem. The bits are stored in the `fsync_components` global which is initialized to `FSYNC_COMPONENTS_DEFAULT` in `environment.c`. It's also set if `core.fsync` is set in the config by `git_default_core_config` and `gvfs-helper.c` does load the default config.

**Comment by derrickstolee** [comment]
This is no longer required, as the real problem is identified in #571.

**Pull request closed without merging**
