### PR TITLE
WIP [DO NOT MERGE] FSMonitor3 onto vfs-2.30.0

### PR DESCRIPTION
**Pull request by jeffhostetler**
This PR merges [pre-RFC] simple-ipc and [WIP] fsmonitor3 onto vfs-2.28.0+jk/strvec for testing purposes.

This PR should replace #282

### CODE REVIEW

**Comment by dscho** [comment]
There are some build issues, apparently. As to vs-build, it fails with [this message](https://github.com/microsoft/git/pull/289/checks?check_run_id=1125426770#step:7:1690):

>          LINK : fatal error LNK1181: cannot open input file 'expat.lib' [D:\a\git\git\git-gvfs-helper.proj\git-gvfs-helper.vcxproj]

This is the well-known change in `vcpkg` that was already addressed upstream. I opened https://github.com/microsoft/git/pull/290 to address this (and would like to fast-track that PR into `vfs-2.28.0`).

The [second issue](https://github.com/microsoft/git/pull/289/checks?check_run_id=1125426957#step:5:250) seems to be in the macOS-specific FSMonitor tests:

> not ok 3 - implicit2 daemon start and stop (rename .git)

It would appear to me as if deleting `.git` did _not_ stop the daemon on macOS. Maybe this is just a little time delay? If you have access to a macOS machine, I would try to run the test with the `--stress` option to figure out whether this is a racy timing issue (AKA flaky). If you don't, I would recommend narrowing down the CI similar to how I did it in dscho/git@1d9fbe8697ddd8c02948656ea489fbb3d5299c93 (i.e. running _only_ the simple-ipc and fsmonitor tests, and only in three OS-specific jobs), and if necessary, use the `tmate` trick to SSH into the macOS agent (imitating dscho/git@548193fd04023501f87034380921bf0020955f18) to be able to dig around interactively.

**Comment by jeffhostetler** [comment]
@dscho Hey thanks for the quick look.  I hadn't seen the expat issue until this morning.  I think I probably had that commit in my upstream + 11th batch version.

WRT the test fail on mac, look at compat/fsmonitor/macos.c.  I put a TODO comment in there describing it.  I'd like to talk to you about expanding the `was_deleted` arg of the fsmonitor_is_special_path call -- much like I did on other platforms.
The existing mac code does a `(event_flags[] & (...was_deleted_bits...)) && lstat())` and I was confused about the 
trailing lstat call.   Adding another `(event_flags[] & (...renamed_away_flags...))` clause would not need the lstat IIUC.
And all of that logic made me want to invert the _is_special function to ONLY compute the deleted flag if the path is
".git" or ".git/" so that we don't waste the lstat.  That's one of the things I wanted to talk to you about today.

**Comment by dscho** [comment]
>  I hadn't seen the expat issue until this morning. I think I probably had that commit in my upstream + 11th batch version

Yes, it's already in upstream's `master` branch.

> The existing mac code does a `(event_flags[] & (...was_deleted_bits...)) && lstat())`

I _think_ that my idea there was to avoid false positives when a directory is replaced by a file (this can happen when you call `git submodule absorbgitdirs` IIRC).

> And all of that logic made me want to invert the _is_special function to ONLY compute the deleted flag if the path is
> ".git" or ".git/" so that we don't waste the lstat.

Good idea!

**Comment by dscho** [comment]
@jeffhostetler this can be closed now, right?

**Comment by jeffhostetler** [comment]
yes, thanks!

**Pull request closed without merging**
