### PR TITLE
FSMonitor

### PR DESCRIPTION
**Pull request by dscho**
This PR supersedes #256, and is rebased on top of vfs-2.27.0.

On purpose, it merges the FSMonitor branch thicket that is based on Git v2.27.0, to maintain easy "upstreamability".

### CODE REVIEW

**Comment by sluongng** [comment]
Few questions:

1. Do you guys have any intention to upstream this to Git Core? 

2. I see that aside from Window and MacOS, there is also Linux support? Does that mean this patch works on Linux? This concern arose from this being a fork from git-for-windows/git.

**Comment by dscho** [comment]
> * Do you guys have any intention to upstream this to Git Core?

Yes.

See #277 for the first part. We're still working on it.

> * I see that aside from Window and MacOS, there is also Linux support? Does that mean this patch works on Linux? This concern arose from this being a fork from git-for-windows/git.

Let me clarify one big misunderstanding: Git for Windows' main branch  compiles on Windows, macOS and Linux, and passes the test suite. This has always been our aim. Almost all of the patches are meant for upstream (with the obvious exceptions as the changed `README.md` which reflects the nature of the fork).

So yes, there is experimental Linux support (with one known bug: when auto-spawning the daemon, the process is sometimes `daemonize()`d too fast, so that the caller cannot connect to the just-spawned daemon. This will need to be fixed somehow, but we're tackling other problems first.

**Comment by derrickstolee** [comment]
> > * I see that aside from Window and MacOS, there is also Linux support? Does that mean this patch works on Linux? This concern arose from this being a fork from git-for-windows/git.
> 
> Let me clarify one big misunderstanding: Git for Windows' main branch compiles on Windows, macOS and Linux, and passes the test suite. This has always been our aim. Almost all of the patches are meant for upstream (with the obvious exceptions as the changed `README.md` which reflects the nature of the fork).

We have also started releasing `.deb` packages at https://github.com/microsoft/git/releases

**Comment by jeffhostetler** [comment]
closing this in favor of #289.

**Pull request closed without merging**
