### PR TITLE
read-cache: make the index write buffer size 2MB to reduce calls into the OS

### PR DESCRIPTION
**Pull request by neerajsi-msft**
The Windows OS repo has an index that occupies >260MB. Git was writing
this index <8K at a time, incurring the cost of going to the kernel and
invoking the filesystem very frequently. This change increases the buffer
size to 2MB to give the OS bigger chunks of data to work with each invocation.

This change reduces the cost of write_in_full under ce_write by 3X. This is only
worth 2% performance in my rebase scenario, but it's a very low-cost change.

Signed-off-by: Neeraj Singh <neerajsi@ntdev.microsoft.com>

### CODE REVIEW

**Comment by neerajsi-msft** [comment]
Maybe this is better for the generic git for windows distribution or for git upstream.  What do you think?

**Comment by derrickstolee** [comment]
> Maybe this is better for the generic git for windows distribution or for git upstream. What do you think?

Hey, @neerajsi-msft. Sorry I dropped this one. I'm not fully sure of the impact that this buffer will have on Git processes. In particular, since it is a global data structure, it might add 2MB to the memory allocation of any Git process, even those that don't touch the index. (I'm not sure about this.)

You'll get better feedback on the Git mailing list. You could [open a PR on gitgitgadget/git](https://github.com/gitgitgadget/git/pulls) to easily submit to the list and get some quick feedback.

My guess is that they might recommend some kind of "lazy load" of the buffer when it is needed. Something like this might work:

```diff
diff --git a/read-cache.c b/read-cache.c
index 29144cf879e..1856f76ee57 100644
--- a/read-cache.c
+++ b/read-cache.c
@@ -2447,8 +2447,8 @@ int repo_index_has_changes(struct repository *repo,
        }
 }
 
-#define WRITE_BUFFER_SIZE 8192
-static unsigned char write_buffer[WRITE_BUFFER_SIZE];
+#define WRITE_BUFFER_SIZE (2 * 1024 * 1024)
+static unsigned char *write_buffer;
 static unsigned long write_buffer_len;
 
 static int ce_write_flush(git_hash_ctx *context, int fd)
@@ -2780,6 +2780,9 @@ static int do_write_index(struct index_state *istate, struct tempfile *tempfile,
        struct index_entry_offset_table *ieot = NULL;
        int nr, nr_threads;
 
+       if (!write_buffer)
+               write_buffer = xmalloc(WRITE_BUFFER_SIZE);
+
        for (i = removed = extended = 0; i < entries; i++) {
                if (cache[i]->ce_flags & CE_REMOVE)
                        removed++;
```

Of course, it causes a test failure in `t0021-conversion.sh`:

```
+ GIT_MMAP_LIMIT=1m GIT_ALLOC_LIMIT=1m git add 30MB
fatal: attempting to allocate 2097152 over limit 1048576
```

So, this isn't an easy problem. Further, this constant-size increase definitely violates some expectations of how large contiguous data sizes should be with `GIT_ALLOC_LIMIT`. (I see that is not [documented with the rest of the environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables).)

**Comment by neerajsi-msft** [comment]
I looked on the git mailing list and see that someone asked this same question before:
https://lore.kernel.org/git/1458577365.9385.31.camel@twopensource.com/

Given that vfs for git isn't going to support split indexes any time soon (not in active development), can we just apply this patch to our fork?  

In terms of memory usage (putting my kernel developer hat on): having a large buffer allocated in .bss like this costs 'commit' which is just a counter in memory of how much memory the OS has promised to give applications.  Unless the buffer is actually accessed, it does not cost "working set" or "reference set", which is the real memory usage of an application.

I will give the git mailing list a shot first tho.

**Comment by neerajsi-msft** [comment]
Hi Derrick,
I went ahead and submitted a core git PR with a more modest write buffer size that still gives us all the benefit.
Could you please /allow me at https://github.com/gitgitgadget/git/pull/877?

Thanks!

**Comment by dscho** [comment]
Isn't this PR superseded by f279894d283101e8e7427347a5469a8731820872?

**Comment by derrickstolee** [comment]
> Isn't this PR superseded by [f279894](https://github.com/microsoft/git/commit/f279894d283101e8e7427347a5469a8731820872)?

Yes. @neerajsi-msft: We will automatically get that change when we rebase the `microsoft/git` code onto the next major Git release. That's how we typically get these changes. This PR can be closed and the next release will include the new buffer size.

**Comment by neerajsi-msft** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dscho** [comment]
> when we rebase the `microsoft/git` code onto the next major Git release

It actually made it into v2.31.0 and therefore into vfs-2.31.0.

**Pull request closed without merging**
