### PR TITLE
[DO NOT MERGE] sparse-checkout in-tree dependencies

### PR DESCRIPTION
**Pull request by derrickstolee**
**THIS IS ONLY A PROTOTYPE**

First, this brings in git/git#724 for improved sparse-checkout updates, allowing us to un-revert the checks for clean status.

Second, this includes a prototype implementation of `git sparse-checkout set --in-tree` that creates a multi-valued config setting `sparse-checkout.inTree`. Each of these values is a "tip" directory that we care about and in each directory we look for a `.gitdependencies` file containing the directories needed for that directory. The sparse-checkout is then defined by those in-tree dependencies.

When updating the index, we refresh the sparse-checkout file with those dependencies. There is a lot to do to make this actually submittable, but I'm creating the PR now to generate an installer for testing.

### CODE REVIEW

**Comment by derrickstolee** [comment]
Possible directions for in-tree format
========================

Based on the prototype, several comments presented alternatives. I didn't do a good job of describing why I landed on the one that I picked, but also there are benefits that I didn't quite see.

First, a few notes about specific questions:

1. _Nothing about this is a DAG._ That's right. It's just a directed graph. Cycles can happen if the data says it should. There's nothing broken about this as far as the implementation. It is resilient to cycles. If someone were to use this as their build DAG they could find problems, but that can happen already with build definitions; the build just breaks when that happens.

2. _The direction doesn't effect the end result._ We are taking the union of all dependent directories, so order doesn't matter. In that way, we are constructing a "set" of directories by walking a graph of sets and taking their union.

3. We do _not_ want to be scanning directories for dependency files. If a dependency says to include a directory "A/B" then that directory "A/B" should include the dependencies for all subdirectories. We will not scan for a dependency file in "A/B/C/D/.../Q". The documentation for this feature should provide a "best practices" guide that mentions the granularity of this feature will likely be different from the exact build system's dependencies. Think instead about how large components interact, and how feature teams require "bags" of projects.

Now, to the options:

In-tree sparse-checkout files
----------------------------------

@dscho brought up this option, and it does match what Minh had originally considered at the contributors summit. In fact, I had even built a version of the prototype with this model.

The issue that makes me think this is not a good way forward is that the files will grow quadratically. In the directed dependency graph of projects, if there are S _sources_ (starting projects that would define a sparse-checkout definition) and there are N total projects, then the resulting data could have O(S*N) lines! If there is a common project that is used by half of the projects, and it adds a dependency, that dependency needs to be injected into S/2 files.

Not only is it a pain that creating one dependency link causes edits across many files, this model is also likely to experience merge pain as adding or removing dependencies from very different projects could easily cause conflicts in the large sparse-checkout definitions.

There is also a logistical problem if these are literal sparse-checkout files: what order do we use when taking the union of two files? If they are in "cone mode" then we could take the semantic union, but that would include merging the files according to directory depth and possibly removing entries that are subdirectories of recursive matches in another file.

Directory dependency digraph with `.gitdependencies` files
-------------------------------------------------------------------

This is the option in the v1 prototype. This does the simplest thing by starting at a directory and picking a list of dependent directories from a well-known filename. This may have multiple issues, as described.

Combination approach: allow interdependent cone files
----------------------------------------------------------------

Basic idea: have files (of arbitrary name) in the repo, and the config option points to a set of files to use to generate the sparse-checkout.

To get around complications with fully-general sparse-checkout definitions, we use the following format on each line:

1. If the line ends with a slash (`/`) then it is a directory that is needed in the cone for this file.
2. If the line does not end with a slash, then it is a file and we take all dependent directories in that file (and any file it references, etc.).

For example, we could have the `A/.deps` file contain:

```
/A/
/B/C/
/D/E/.deps
```

and `D/E/.deps` contains

```
/D/E/
/D/F/
```

So the resulting directories included by sparse-checkout are `A`, `B/C`, `D/E`, and `D/F`.

**Comment by dscho** [comment]
> The issue that makes me think this is not a good way forward is that the files will grow quadratically. In the directed dependency graph of projects, if there are S _sources_ (starting projects that would define a sparse-checkout definition) and there are N total projects, then the resulting data could have O(S*N) lines! If there is a common project that is used by half of the projects, and it adds a dependency, that dependency needs to be injected into S/2 files.

Hrm. I had not anticipated that, indeed. And now I wonder whether we can have any solution that is simple in the common case, yet powerful enough to cover the complicated cases.

**Comment by derrickstolee** [comment]
> > The issue that makes me think this is not a good way forward is that the files will grow quadratically. In the directed dependency graph of projects, if there are S _sources_ (starting projects that would define a sparse-checkout definition) and there are N total projects, then the resulting data could have O(S*N) lines! If there is a common project that is used by half of the projects, and it adds a dependency, that dependency needs to be injected into S/2 files.
> 
> Hrm. I had not anticipated that, indeed. And now I wonder whether we can have any solution that is simple in the common case, yet powerful enough to cover the complicated cases.

The good thing about option (3) is that it does both: you can have a static list of directories with no file references. It's very similar to what you suggested, but we restrict it to only cone-mode lists and not general sparse-checkout files.

**Comment by dscho** [comment]
One thing about option three worries me, though: the magic distinction between directories (ignore!) and files (read and parse!). We already have our share of hard-to-explain concepts in Git, and I would wish that we found ways to change them that require less documentation (because users will look at the feature and "get it" right away).

**Pull request closed without merging**
