### PR TITLE
macOS/brew: let the build find gettext headers/libraries/msgfmt

### PR DESCRIPTION
**Pull request by dscho**
This is a companion to https://github.com/gitgitgadget/git/pull/616, as it seems we need this to build Git in our Pipelines.

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
Thank you so much for this!

**Comment by derrickstolee** [comment]
I [started an installer build](https://dev.azure.com/gvfs/ci/_build/results?buildId=18572&view=results) to double-check that it fixes us there, too.

**Comment by dscho** [comment]
> I [started an installer build](https://dev.azure.com/gvfs/ci/_build/results?buildId=18572&view=results) to double-check that it fixes us there, too.

Good call! It passed the macOS part with success, so I'll merge this here PR.

**Comment by jeffhostetler** [comment]
wow!  what a pain!  thanks!

**Pull request merged**
