### PR TITLE
[DO NOT MERGE] Tentative vfs-2.25.0 branch

### PR DESCRIPTION
**Pull request by derrickstolee**
Rebased onto `v2.25.0-rc0.windows.1`.

Merge issues:

1. Dropped our version of the sparse-checkout feature in favor of the one in `v2.25.0-rc0`. This led to a lot of re-applying the merges that were included.
2. A few simple near-edit conflicts were fixed.
3. One bit of virtualized filesystem code was moved into a helper method.
4. The `gvfs-helper.c` needed an update due to dropping the `sha1_to_hex_r()` method.
5. The upstream version of sparse-checkout looks for a dirty status before updating. That behavior does not match what we were using. Revert that commit for now until both versions "do the right thing". See #234.
6. Removed the multi-pack-index progress commit in favor of the upstream version.

Range Diff:
```  1:  77844cabe6 <   -:  ---------- sparse-checkout: create builtin with 'list' subcommand
  2:  7e12ce4c40 <   -:  ---------- sparse-checkout: create 'init' subcommand
  3:  2e885711e4 <   -:  ---------- clone: add --sparse mode
  4:  c6b249a6e1 <   -:  ---------- sparse-checkout: 'set' subcommand
  5:  ead918f126 <   -:  ---------- sparse-checkout: add '--stdin' option to set subcommand
  6:  043e1a3d9a <   -:  ---------- sparse-checkout: create 'disable' subcommand
  7:  d97f70b862 <   -:  ---------- trace2: add region in clear_ce_flags
  8:  95a6be78f3 <   -:  ---------- sparse-checkout: add 'cone' mode
  9:  fa1e8e3adb <   -:  ---------- sparse-checkout: use hashmaps for cone patterns
 10:  93f2e4e9df <   -:  ---------- sparse-checkout: init and set in cone mode
 11:  b2522a9757 <   -:  ---------- unpack-trees: hash less in cone mode
 12:  705f31cb7b <   -:  ---------- unpack-trees: add progress to clear_ce_flags()
 13:  4326bc1811 <   -:  ---------- read-tree: show progress by default
 14:  f9e96bf90e <   -:  ---------- sparse-checkout: sanitize for nested folders
 15:  efd9c53b6d <   -:  ---------- sparse-checkout: update working directory in-process
 16:  a879c5bfb5 <   -:  ---------- sparse-checkout: write using lockfile
 17:  20e7bd3da4 <   -:  ---------- sparse-checkout: cone mode should not interact with .gitignore
 18:  3fb28e041f !   1:  21f524c5ac reset --stdin: trim carriage return from the paths
    @@ Commit message
     
         Signed-off-by: Kevin Willford <kewillf@microsoft.com>
     
    - ## builtin/reset.c ##
    -@@ builtin/reset.c: int cmd_reset(int argc, const char **argv, const char *prefix)
    - 
    - 	if (read_from_stdin) {
    - 		strbuf_getline_fn getline_fn = nul_term_line ?
    --			strbuf_getline_nul : strbuf_getline_lf;
    -+			strbuf_getline_nul : strbuf_getline;
    - 		int flags = PATHSPEC_PREFER_FULL;
    - 		struct strbuf buf = STRBUF_INIT;
    - 		struct strbuf unquoted = STRBUF_INIT;
    -
      ## t/t7108-reset-stdin.sh ##
     @@ t/t7108-reset-stdin.sh: test_expect_success '--stdin requires --mixed' '
      	git reset --mixed --stdin <list
 19:  bd680f969b !   2:  007e3b76f6 gvfs: start by adding the -gvfs suffix to the version
    @@ GIT-VERSION-GEN
      #!/bin/sh
      
      GVF=GIT-VERSION-FILE
    --DEF_VER=v2.24.0
    -+DEF_VER=v2.24.0.vfs.1.1
    +-DEF_VER=v2.25.0
    ++DEF_VER=v2.25.0.vfs.1.1
      
      LF='
      '
 20:  65ae8d9394 =   3:  b84ed5db2d gvfs: ensure that the version is based on a GVFS tag
 21:  824126e835 =   4:  281dd65821 gvfs: add a GVFS-specific header file
 22:  9517942018 !   5:  91a7f1fb37 gvfs: add the core.gvfs config setting
    @@ Documentation/config/core.txt: core.multiPackIndex::
     +	Enable the features needed for GVFS.
     +
      core.sparseCheckout::
    - 	Enable "sparse checkout" feature. See section "Sparse checkout" in
    - 	linkgit:git-read-tree[1] for more information.
    + 	Enable "sparse checkout" feature. See linkgit:git-sparse-checkout[1]
    + 	for more information.
     
      ## cache.h ##
     @@ cache.h: extern char *git_replace_ref_base;
    + 
      extern int fsync_object_files;
      extern int core_preload_index;
    - extern int core_apply_sparse_checkout;
     +extern int core_gvfs;
      extern int precomposed_unicode;
      extern int protect_hfs;
    @@ config.c: static int git_default_core_config(const char *var, const char *value,
      		return 0;
     
      ## environment.c ##
    -@@ environment.c: enum object_creation_mode object_creation_mode = OBJECT_CREATION_MODE;
    - char *notes_ref_name;
    +@@ environment.c: char *notes_ref_name;
      int grafts_replace_parents = 1;
      int core_apply_sparse_checkout;
    + int core_sparse_checkout_cone;
     +int core_gvfs;
      int merge_log_config = -1;
      int precomposed_unicode = -1; /* see probe_utf8_pathname_composition() */
 23:  85522d89d6 !   6:  70b4dc4ad4 gvfs: add the feature to skip writing the index' SHA-1
    @@ Documentation/config/core.txt: core.multiPackIndex::
     +--
      
      core.sparseCheckout::
    - 	Enable "sparse checkout" feature. See section "Sparse checkout" in
    + 	Enable "sparse checkout" feature. See linkgit:git-sparse-checkout[1]
     
      ## gvfs.h ##
     @@
 24:  84cfc77840 =   7:  5e5e1e8ec9 gvfs: add the feature that blobs may be missing
 25:  321460f206 =   8:  60a637a94f gvfs: prevent files to be deleted outside the sparse checkout
 26:  f4a8a9de37 =   9:  52a4cfa1c7 gvfs: optionally skip reachability checks/upload pack during fetch
 27:  9e3f7d3df1 =  10:  edcfc9df8c gvfs: ensure all filters and EOL conversions are blocked
 28:  85879a03e7 =  11:  73b32c42ed Add a new run_hook_argv() function
 29:  7607235039 =  12:  bad623023e gvfs: allow "virtualizing" objects
 30:  69e6306ac8 =  13:  4e74c191d2 Hydrate missing loose objects in check_and_freshen()
 31:  f8349b13fe =  14:  425c1571a5 Add support for read-object as a background process to retrieve missing objects
 32:  ae0134c9ee =  15:  b90204f9df sha1_file: when writing objects, skip the read_object_hook
 33:  420a9cc810 =  16:  6ee953bee7 gvfs: add global command pre and post hook procs
 34:  f2a4c3c805 =  17:  22c4659a45 Allow hooks to be run before setup_git_directory()
 35:  1a21ea5a00 =  18:  91291005db gvfs: introduce pre/post command hooks
 36:  7b5b3c2950 =  19:  665d8a0771 sparse-checkout: update files with a modify/delete conflict
 37:  25b40c3784 =  20:  da43a06898 t0400: verify that the hook is called correctly from a subdirectory
 38:  5c319b977e =  21:  71383272cb sparse-checkout: avoid writing entries with the skip-worktree bit
 39:  dcbb31aeae =  22:  6f4062d600 Pass PID of git process to hooks.
 40:  f0dd34f654 =  23:  eb9bcc7626 Fix reset when using the sparse-checkout feature.
 41:  44a92a889d =  24:  27b8f6d795 pre-command: always respect core.hooksPath
 42:  5e23229807 =  25:  6f1c19016c Do not remove files outside the sparse-checkout
 43:  85f4abef03 =  26:  fa5d4abca0 gvfs: refactor loading the core.gvfs config value
 44:  427208a591 =  27:  ba96ed82bf cache-tree: remove use of strbuf_addf in update_one
 45:  e21a19957c =  28:  db3c3fc3cd status: add status serialization mechanism
 46:  a4fd66cf50 =  29:  e18a0aa695 Teach ahead-behind and serialized status to play nicely together
 47:  35755e9692 =  30:  b7a47a3992 status: serialize to path
 48:  9dc241d9a2 =  31:  c11afa2df8 status: reject deserialize in V2 and conflicts
 49:  e711ae3e12 !  32:  c827fd2eb7 Add virtual file system settings and hook proc
    @@ Makefile: LIB_OBJS += utf8.o
     
      ## cache.h ##
     @@ cache.h: extern char *git_replace_ref_base;
    + 
      extern int fsync_object_files;
      extern int core_preload_index;
    - extern int core_apply_sparse_checkout;
     +extern const char *core_virtualfilesystem;
      extern int core_gvfs;
      extern int precomposed_unicode;
    @@ dir.c
      /*
       * Tells read_directory_recursive how a file or directory should be treated.
     @@ dir.c: enum pattern_match_result path_matches_pattern_list(
    - 				struct index_state *istate)
    - {
    - 	struct path_pattern *pattern;
    -+
    + 	int result = NOT_MATCHED;
    + 	const char *slash_pos;
    + 
     +	/*
     +	 * The virtual file system data is used to prevent git from traversing
     +	 * any part of the tree that is not in the virtual file system.  Return
    @@ dir.c: enum pattern_match_result path_matches_pattern_list(
     +	if (is_excluded_from_virtualfilesystem(pathname, pathlen, *dtype) > 0)
     +		return 1;
     +
    - 	pattern = last_matching_pattern_from_list(pathname, pathlen, basename,
    - 						  dtype, pl, istate);
    - 	if (pattern) {
    + 	if (!pl->use_cone_patterns) {
    + 		pattern = last_matching_pattern_from_list(pathname, pathlen, basename,
    + 							dtype, pl, istate);
     @@ dir.c: struct path_pattern *last_matching_pattern(struct dir_struct *dir,
      int is_excluded(struct dir_struct *dir, struct index_state *istate,
      		const char *pathname, int *dtype_p)
    @@ dir.c: static enum path_treatment treat_one_path(struct dir_struct *dir,
      	/*
      	 * When we are looking at a directory P in the working tree,
      	 * there are three cases:
    -@@ dir.c: static enum path_treatment read_directory_recursive(struct dir_struct *dir,
    - 		/* add the path to the appropriate result list */
    - 		switch (state) {
    - 		case path_excluded:
    -+			if (is_excluded_from_virtualfilesystem(path.buf, path.len, DT_DIR) > 0)
    -+				break;
    - 			if (dir->flags & DIR_SHOW_IGNORED)
    - 				dir_add_name(dir, istate, path.buf, path.len);
    - 			else if ((dir->flags & DIR_SHOW_IGNORED_TOO) ||
    +@@ dir.c: static void add_path_to_appropriate_result_list(struct dir_struct *dir,
    + 	/* add the path to the appropriate result list */
    + 	switch (state) {
    + 	case path_excluded:
    ++		if (is_excluded_from_virtualfilesystem(path->buf, path->len, DT_DIR) > 0)
    ++			break;
    + 		if (dir->flags & DIR_SHOW_IGNORED)
    + 			dir_add_name(dir, istate, path->buf, path->len);
    + 		else if ((dir->flags & DIR_SHOW_IGNORED_TOO) ||
     
      ## environment.c ##
    -@@ environment.c: char *notes_ref_name;
    - int grafts_replace_parents = 1;
    +@@ environment.c: int grafts_replace_parents = 1;
      int core_apply_sparse_checkout;
    + int core_sparse_checkout_cone;
      int core_gvfs;
     +const char *core_virtualfilesystem;
      int merge_log_config = -1;
    @@ unpack-trees.c: static int clear_ce_flags_1(struct index_state *istate,
      			break;
      
     @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
    - 	if (!core_apply_sparse_checkout || !o->update)
    - 		o->skip_sparse_checkout = 1;
    - 	if (!o->skip_sparse_checkout) {
    --		char *sparse = git_pathdup("info/sparse-checkout");
    + 	if (!o->skip_sparse_checkout && !o->pl) {
    + 		char *sparse = git_pathdup("info/sparse-checkout");
    + 		pl.use_cone_patterns = core_sparse_checkout_cone;
     -		if (add_patterns_from_file_to_list(sparse, "", 0, &pl, NULL) < 0)
     -			o->skip_sparse_checkout = 1;
     -		else
    -+		if (core_virtualfilesystem) {
    ++		if (core_virtualfilesystem)
      			o->pl = &pl;
     -		free(sparse);
    -+		} else {
    ++		else if (add_patterns_from_file_to_list(sparse, "", 0, &pl, NULL) < 0)
    ++			o->skip_sparse_checkout = 1;
    ++		else {
     +			char *sparse = git_pathdup("info/sparse-checkout");
     +			if (add_patterns_from_file_to_list(sparse, "", 0, &pl, NULL) < 0)
     +				o->skip_sparse_checkout = 1;
    @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpac
     +		 * If they will have NEW_SKIP_WORKTREE, also set CE_SKIP_WORKTREE
      		 * so apply_sparse_checkout() won't attempt to remove it from worktree
      		 */
    - 		mark_new_skip_worktree(o->pl, &o->result, CE_ADDED, CE_SKIP_WORKTREE | CE_NEW_SKIP_WORKTREE);
    + 		mark_new_skip_worktree(o->pl, &o->result,
     
      ## virtualfilesystem.c (new) ##
     @@
 50:  397b4e74c5 =  33:  527e28e21c Update the virtualfilesystem support
 51:  31d1e5fcb6 =  34:  96ba4eadec virtualfilesystem: don't run the virtual file system hook if the index has been redirected
 52:  a39fac894f =  35:  949b596eae virtualfilesystem: fix bug with symlinks being ignored
 53:  aaf26eb855 =  36:  06187e1845 virtualfilesystem: check if directory is included
 54:  10c035eeec =  37:  53136aa648 vfs: fix case where directories not handled correctly
 55:  b8e8631e63 =  38:  6f32da2dbe commit: add generation to pop_most_recent_commit()
 56:  8a10c7ba53 =  39:  2acc657e20 status: fix rename reporting when using serialization cache
 57:  29b2342a6f =  40:  fbf83a36e3 status: add comments for ahead_behind_flags in serialization
 58:  c4b5aa82ce =  41:  607ed43623 serialize-status: serialize global and repo-local exclude file metadata
 59:  a4793fa734 =  42:  c9f635c8dd status: deserialization wait
 60:  c372afa2d9 =  43:  bcba7d3adf rebase/stash: make post-command hook work again
 61:  776e875f1e !  44:  7c9dca420b fsck: use ERROR_MULTI_PACK_INDEX
    @@ builtin/fsck.c: static int name_objects;
      #define ERROR_COMMIT_GRAPH 020
     +#define ERROR_MULTI_PACK_INDEX 040
      
    - static const char *describe_object(struct object *obj)
    + static const char *describe_object(const struct object_id *oid)
      {
     @@ builtin/fsck.c: int cmd_fsck(int argc, const char **argv, const char *prefix)
      			midx_argv[2] = "--object-dir";
 62:  eeca8b4e93 !  45:  c17eb7cc21 send-pack: do not check for sha1 file when GVFS_MISSING_OK set
    @@ send-pack.c: static int send_pack_config(const char *var, const char *value, voi
      {
     -	if (negative &&
     +	if (negative && !gvfs_config_is_set(GVFS_MISSING_OK) &&
    - 	    !has_object_file_with_flags(oid, OBJECT_INFO_SKIP_FETCH_OBJECT))
    - 		return;
    - 
    + 	    !has_object_file_with_flags(oid,
    + 					OBJECT_INFO_SKIP_FETCH_OBJECT |
    + 					OBJECT_INFO_QUICK))
 63:  33c42b2bdb =  46:  5b05fa082a gvfs: block unsupported commands when running in a GVFS repo
 64:  cca9547dc2 =  47:  2009015df8 BRANCHES.md: Add explanation of branches and using forks
 65:  b68f0357fc =  48:  28e93dfc6c gvfs:trace2:data: add trace2 tracing around read_object_process
 66:  b0a13fa27f =  49:  0961a9b46d gvfs:trace2:data: status deserialization information
 67:  ea8b7894ff =  50:  13a32d2ec1 gvfs:trace2:data: status serialization
 68:  7ce21a8d48 =  51:  2f67571a79 gvfs:trace2:data: add vfs stats
 69:  7c800a8085 =  52:  8a21c5bf4d trace2: refactor setting process starting time
 70:  789e3b61ae <   -:  ---------- trace2:gvfs:experiment: clear_ce_flags_1
  -:  ---------- >  53:  e5b8e5c3bc trace2:gvfs:experiment: clear_ce_flags_1
 71:  cca0d1160b =  54:  2fe4d62587 trace2:gvfs:experiment: traverse_trees
 72:  cf616073f3 =  55:  bd77e92559 trace2:gvfs:experiment: report_tracking
 73:  90cca84a1e =  56:  bc8c2f5519 trace2:gvfs:experiment: read_cache: annotate thread usage in read-cache
 74:  509f7361f8 =  57:  7b30b3d24a trace2:gvfs:experiment: read-cache: time read/write of cache-tree extension
 75:  5d4d2e21a9 =  58:  e0cd39d381 trace2:gvfs:experiment: add prime_cache_tree region
 76:  b6b0a424bd =  59:  65211e263a trace2:gvfs:experiment: add region to apply_virtualfilesystem()
 77:  c0086f9366 !  60:  43a83ea781 trace2:gvfs:experiment: add region around unpack_trees()
    @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpac
      	memset(&pl, 0, sizeof(pl));
      	if (!core_apply_sparse_checkout || !o->update)
     @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
    - done:
      	trace_performance_leave("unpack_trees");
    - 	clear_pattern_list(&pl);
    + 	if (!o->keep_pattern_list)
    + 		clear_pattern_list(&pl);
     +	trace2_region_leave("exp", "unpack_trees", NULL);
      	return ret;
      
 78:  428603d022 =  61:  095e83bef4 trace2:gvfs:experiment: add region to cache_tree_fully_valid()
 82:  4c88296b81 !  62:  0b900bc336 trace2:gvfs:experiment: add unpack_entry() counter to unpack_trees() and report_tracking()
    @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpac
      	trace_performance_enter();
      	memset(&pl, 0, sizeof(pl));
     @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
    - done:
      	trace_performance_leave("unpack_trees");
    - 	clear_pattern_list(&pl);
    + 	if (!o->keep_pattern_list)
    + 		clear_pattern_list(&pl);
     +	trace2_data_intmax("unpack_trees", NULL, "unpack_trees/nr_unpack_entries",
     +			   (intmax_t)(get_nr_unpack_entry() - nr_unpack_entry_at_start));
      	trace2_region_leave("exp", "unpack_trees", NULL);
 83:  f67bcaff54 =  63:  a06f59b2cd trace2:gvfs:experiment: increase default event depth for unpack-tree data
 84:  26b04b0c9d !  64:  8b26800393 trace2:gvfs:experiment: add data for check_updates() in unpack_trees()
    @@ unpack-trees.c: static int check_updates(struct unpack_trees_options *o)
      	return errs != 0;
      }
     @@ unpack-trees.c: static int clear_ce_flags(struct index_state *istate,
    - 
    - 	strbuf_reset(&prefix);
    + 					_("Updating index flags"),
    + 					istate->cache_nr);
      
     -	xsnprintf(label, sizeof(label), "clear_ce_flags(0x%08lx,0x%08lx)",
     +	xsnprintf(label, sizeof(label), "clear_ce_flags/0x%08lx_0x%08lx",
      		  (unsigned long)select_mask, (unsigned long)clear_mask);
    --	trace2_region_enter("exp", label, the_repository);
    -+	trace2_region_enter("unpack_trees", label, the_repository);
    + 	trace2_region_enter("unpack_trees", label, the_repository);
    +-
      	rval = clear_ce_flags_1(istate,
      				istate->cache,
      				istate->cache_nr,
    - 				&prefix,
    - 				select_mask, clear_mask,
    - 				pl, 0);
    --	trace2_region_leave("exp", label, the_repository);
    -+	trace2_region_leave("unpack_trees", label, the_repository);
    - 
    - 	return rval;
    - }
     @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
      	if (len > MAX_UNPACK_TREES)
      		die("unpack_trees takes at most %d trees", MAX_UNPACK_TREES);
    @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpac
      		if (ret < 0)
      			goto return_failed;
     @@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
    - 	clear_pattern_list(&pl);
    + 		clear_pattern_list(&pl);
      	trace2_data_intmax("unpack_trees", NULL, "unpack_trees/nr_unpack_entries",
      			   (intmax_t)(get_nr_unpack_entry() - nr_unpack_entry_at_start));
     -	trace2_region_leave("exp", "unpack_trees", NULL);
 85:  370a085719 =  65:  81d3a78431 Trace2:gvfs:experiment: capture more 'tracking' details
 86:  c7215a1ad4 =  66:  03f4d2b2c3 merge-recursive: avoid confusing logic in was_dirty()
 87:  492477591f =  67:  3df82fa345 merge-recursive: add some defensive coding to was_dirty()
 88:  1ddd87f815 =  68:  f4d43a1ff1 merge-recursive: teach was_dirty() about the virtualfilesystem
 89:  0abbb41560 =  69:  46dba7d08a status: deserialize with -uno does not print correct hint
 79:  9be8c92d70 =  70:  3f74d141fc t5516: relax error message pattern
 80:  4889b6d7a4 =  71:  4c035cda7e upload-pack: fix race condition in error messages
 81:  665d5204d7 <   -:  ---------- multi-pack-index: add --no-progress to verify
 90:  3a22eb5402 =  72:  59fd64e17c backwards-compatibility: support the post-indexchanged hook
 91:  3641e26973 <   -:  ---------- fsmonitor: fix watchman integration
 92:  5a5aefda1d =  73:  c54c4615a1 credential: set trace2_child_class for credential manager children
 93:  fc9c77fe77 =  74:  1e584fe0f6 sub-process: do not borrow cmd pointer from caller
 94:  3019adb067 =  75:  93452626c1 sub-process: add subprocess_start_argv()
 95:  15d8415ded =  76:  e18f4c8a14 sha1-file: add function to update existing loose object cache
 96:  8259260346 !  77:  1dcbb84ed3 packfile: add install_packed_git_and_mru()
    @@ Commit message
     
      ## packfile.c ##
     @@ packfile.c: void install_packed_git(struct repository *r, struct packed_git *pack)
    - 	r->objects->packed_git = pack;
    + 	hashmap_add(&r->objects->pack_map, &pack->packmap_ent);
      }
      
     +void install_packed_git_and_mru(struct repository *r, struct packed_git *pack)
 97:  abfc0a4022 =  78:  a710a93136 index-pack: avoid immediate object fetch while parsing packfile
 98:  706d2aec7a =  79:  f629b0e0d1 gvfs-helper: create tool to fetch objects using the GVFS Protocol
 99:  73d2d384fd =  80:  d4370304a2 gvfs-helper: fix race condition when creating loose object dirs
100:  7f68d1da5f =  81:  9a93c9ad17 sha1-file: create shared-cache directory if it doesn't exist
101:  c478dfbc2c =  82:  aac7a3bb5a gvfs-helper-client: rename ghs__ symbols to gh_server__
102:  1c31a8c12e =  83:  a7f1e5e251 gvfs-helper-client: rename ghs__chosen_odb to gh_client__chosen_odb for clarity
103:  16e40b32af =  84:  a6c494e822 gvfs-helper-client: rename ghc__ symbols to gh_client__ for clarity
104:  617fd0555e =  85:  4afb0d1a68 gvfs-helper: better handling of network errors
105:  891a51b40c =  86:  7a1e574ede gvfs-helper-client: properly update loose cache with fetched OID
106:  df4a8db155 =  87:  f7dce93635 gvfs-helper: V2 robust retry and throttling
107:  ae0c9ccdfe =  88:  e765163b60 gvfs-helper: expose gvfs/objects GET and POST semantics
108:  740de11def !  89:  c35b525322 gvfs-helper: dramatically reduce progress noise
    @@ gvfs-helper.c: static void setup_gvfs_objects_progress(struct gh__request_params
      }
      
      /*
    -
    - ## unpack-trees.c ##
    -@@ unpack-trees.c: int unpack_trees(unsigned len, struct tree_desc *t, struct unpack_trees_options
    - 	memset(&pl, 0, sizeof(pl));
    - 	if (!core_apply_sparse_checkout || !o->update)
    - 		o->skip_sparse_checkout = 1;
    --	if (!o->skip_sparse_checkout) {
    -+	if (!o->skip_sparse_checkout && !o->pl) {
    - 		if (core_virtualfilesystem) {
    - 			o->pl = &pl;
    - 		} else {
109:  8cf9286267 =  90:  69d9dffd8c gvfs-helper-client.h: define struct object_id
110:  1deef249a9 =  91:  c25566ee67 gvfs-helper: handle pack-file after single POST request
111:  e896e9dfe1 =  92:  ee2d76fe85 test-gvfs-prococol, t5799: tests for gvfs-helper
112:  3adadbc41e =  93:  955e2df361 t/helper/.gitignore: add test-gvfs-procotol
113:  2857cf81eb =  94:  f096355753 gvfs-helper: move result-list construction into install functions
114:  7706794db5 =  95:  4d18c7721d t5799: add support for POST to return either a loose object or packfile
115:  7f6b47c21d =  96:  3d7cfb5cbf t5799: cleanup wc-l and grep-c lines
116:  7621a6f434 <   -:  ---------- fsmonitor: do not compare bitmap size with size of split index
117:  c633d91f73 <   -:  ---------- fsmonitor: check CE_FSMONITOR_VALID in ce_uptodate
  -:  ---------- >  97:  e9b05d56c3 fsmonitor: check CE_FSMONITOR_VALID in ce_uptodate
118:  87c1478979 =  98:  49b47a0b4f fsmonitor: add script for debugging and update script for tests
119:  be9f2151e2 !  99:  3452d42d46 gvfs-helper: add prefetch support
    @@ gvfs-helper.c: static void create_tempfile_for_loose(
     +	struct tempfile *tempfile_idx = NULL;
     +	int result = -1;
     +	int b_no_idx_in_multipack;
    -+	unsigned char packfile_checksum[GIT_MAX_RAWSZ];
    ++	struct object_id packfile_checksum;
     +	char hex_checksum[GIT_MAX_HEXSZ + 1];
     +	struct strbuf buf_timestamp = STRBUF_INIT;
     +	struct strbuf temp_path_pack = STRBUF_INIT;
    @@ gvfs-helper.c: static void create_tempfile_for_loose(
     +	struct strbuf final_path_idx = STRBUF_INIT;
     +	struct strbuf final_filename = STRBUF_INIT;
     +
    -+	memset(packfile_checksum, 0, sizeof(packfile_checksum));
    -+
     +	if (xread(fd_multipack, &ph, sizeof(ph)) != sizeof(ph)) {
     +		strbuf_addf(&status->error_message,
     +			    "could not read header for packfile[%d] in multipack",
    @@ gvfs-helper.c: static void create_tempfile_for_loose(
     +	result = my_copy_fd_len_tail(fd_multipack,
     +				     get_tempfile_fd(tempfile_pack),
     +				     ph.pack_len,
    -+				     packfile_checksum,
    ++				     packfile_checksum.hash,
     +				     GIT_SHA1_RAWSZ);
     +	if (result < 0){
      		strbuf_addf(&status->error_message,
    @@ gvfs-helper.c: static void create_tempfile_for_loose(
     +	strbuf_addstr(&temp_path_pack, get_tempfile_path(tempfile_pack));
     +	close_tempfile_gently(tempfile_pack);
     +
    -+	sha1_to_hex_r(hex_checksum, packfile_checksum);
    ++	oid_to_hex_r(hex_checksum, &packfile_checksum);
     +
     +	if (b_no_idx_in_multipack) {
      		/*
    @@ gvfs-helper.c: static void do__http_post__gvfs_objects(struct gh__response_statu
     +	struct find_last_data data;
     +
     +	memset(&data, 0, sizeof(data));
    -+	
    ++
     +	for_each_file_in_pack_dir(gh__global.buf_odb_path.buf, cb_find_last, &data);
     +
     +	*last = data.timestamp;
120:  5b190ba311 = 100:  adb6ce7a0a gvfs-helper: add prefetch .keep file for last packfile
121:  88f9f28995 = 101:  ae319fa922 gvfs-helper: do one read in my_copy_fd_len_tail()
122:  a942fc75b2 = 102:  dabc2c38a1 gvfs-helper: move content-type warning for prefetch packs
123:  d4f11868fa ! 103:  84b1aa8b2d fetch: use gvfs-helper prefetch under config
    @@ builtin/fetch.c
      #define FORCED_UPDATES_DELAY_WARNING_IN_MS (10 * 1000)
      
     @@ builtin/fetch.c: int cmd_fetch(int argc, const char **argv, const char *prefix)
    - 
    - 	fetch_if_missing = 0;
    + 		}
    + 	}
      
     +	if (core_gvfs & GVFS_PREFETCH_DURING_FETCH)
     +		gh_client__prefetch(0, NULL);
124:  7f8481bc14 ! 104:  61def50d4f fetch: add --no-update-remote-refs
    @@ Documentation/fetch-options.txt: endif::git-pull[]
      	Use IPv4 addresses only, ignoring IPv6 addresses.
     
      ## builtin/fetch.c ##
    -@@ builtin/fetch.c: static struct refspec refmap = REFSPEC_INIT_FETCH;
    - static struct list_objects_filter_options filter_options;
    +@@ builtin/fetch.c: static struct list_objects_filter_options filter_options;
      static struct string_list server_options = STRING_LIST_INIT_DUP;
      static struct string_list negotiation_tip = STRING_LIST_INIT_NODUP;
    + static int fetch_write_commit_graph = -1;
     +static int update_remote_refs = 1;
      
      static int git_fetch_config(const char *k, const char *v, void *cb)
      {
     @@ builtin/fetch.c: static struct option builtin_fetch_options[] = {
    - 		 N_("run 'gc --auto' after fetching")),
    - 	OPT_BOOL(0, "show-forced-updates", &fetch_show_forced_updates,
      		 N_("check for forced-updates on all updated branches")),
    + 	OPT_BOOL(0, "write-commit-graph", &fetch_write_commit_graph,
    + 		 N_("write the commit-graph after fetching")),
     +	OPT_BOOL(0, "update-remote-refs", &update_remote_refs,
     +		 N_("update the refs/remotes/ refspace")),
      	OPT_END()
125:  b22f1ece30 = 105:  dd08b256be gvfs-helper: better support for concurrent packfile fetches
126:  789f5dd45c = 106:  1c677fdfdb gvfs-helper: retry when creating temp files
  -:  ---------- > 107:  a67b734f41 Revert "sparse-checkout: check for dirty status"
  -:  ---------- > 108:  13e731aef8 Revert "dir: synchronize treat_leading_path() and read_directory_recursive()"
  -:  ---------- > 109:  ff1c1f502c Revert "dir: fix checks on common prefix directory"
```

### CODE REVIEW

**Comment by dscho** [comment]
> [@derrickstolee ](/derrickstolee)
> ` [Merge tag 'v2.24.1.windows.2' into vfs-2.24.1](/microsoft/git/pull/233/commits/5038979a5399c9096798f8a0c981af7166af0778) `

Is this really `v2.24.1.windows.2` and not `v2.25.0-rc0.windows.1`?

**Comment by derrickstolee** [comment]
It took longer than I'd hoped, but I finally managed to get a clean build in microsoft/vfsforgit#1626. However, it required reverting a couple commits from core Git. Hopefully we can find out the right way to integrate with these commits instead.

* In c5c4eddd56ccd2ffd6a193856a660573993e9a41, a switch statement was moved into a new method, `add_path_to_appropriate_result_list()`. We have an integration point for the virtualization hook in that switch, but it is easy to move that into the new method.
* b9670c1f5e6b98837c489a03ac0d343d30e08505 adds callers to `add_path_to_appropriate_result_list()` when scanning common prefixes of pathspecs.
* 777b420347649f26022bb1a4bf7afe7c4fe0b090 adds another caller for another odd case.

I was only able to get a clean VFS for Git build after reverting both 777b420347649f26022bb1a4bf7afe7c4fe0b090 and b9670c1f5e6b98837c489a03ac0d343d30e08505. Previous attempts included:

1. Not moving the virtualization hook integration with the switch and instead only including it before the previous caller.
2. Including the virtualization hook on only a subset of the callers to `add_path_to_appropriate_result_list()`.

None of these simple attempts worked.

Let's dig a little bit into the example that fails. The functional test creates an untracked file and holds a handle on it while trying to clean it with Git. The test is mostly about respecting that handle, but after the handle is cleared we run `git clean -f <untracked-path>`. This path is inside a directory, so we are definitely working with a given pathspec and it has leading directories.

The biggest confusing part is that I cannot repro this behavior in "vanilla" Git. Somehow our virtualized environment is interacting badly here.

Anyone have ideas? Cc: @kewillford, @jeffhostetler, @dscho. Thanks in advance.

**Comment by jeffhostetler** [comment]
Windows builds are failing with a missing "libeay32.dll".   Did something in the VMs get updated/broken?

**Comment by derrickstolee** [comment]
> * [b9670c1](https://github.com/microsoft/git/commit/b9670c1f5e6b98837c489a03ac0d343d30e08505) adds callers to `add_path_to_appropriate_result_list()` when scanning common prefixes of pathspecs.

@kewillford delivered a repro that this causes a `git clean -f` failure in vanilla Git. I'll create a patch and send it upstream. Meanwhile, we should take a version with the reverts and then drop those reverts in the next version, assuming that the bug gets fixed by then.

**Comment by derrickstolee** [comment]
See gitgitgadget/git#526 for the test patch.

**Comment by derrickstolee** [comment]
> Windows builds are failing with a missing "libeay32.dll". Did something in the VMs get updated/broken?

@dscho is this something you know about?

**Comment by dscho** [comment]
> > Windows builds are failing with a missing "libeay32.dll". Did something in the VMs get updated/broken?
> 
> @dscho is this something you know about?

Yes, I just merged the fix into Git for Windows: https://github.com/git-for-windows/git/pull/2476. Maybe you want to sneak it into this PR, too?

**Comment by dscho** [comment]
🎉

**Comment by derrickstolee** [comment]
> > > Windows builds are failing with a missing "libeay32.dll". Did something in the VMs get updated/broken?
> > 
> > 
> > @dscho is this something you know about?
> 
> Yes, I just merged the fix into Git for Windows: [git-for-windows#2476](https://github.com/git-for-windows/git/pull/2476). Maybe you want to sneak it into this PR, too?

Sorry, I completely missed this. I'll open a PR against `vfs-2.25.0` to fix the builds.

**Pull request merged**
