### PR TITLE
[DO-NOT-MERGE] scalar: the game plan

### PR DESCRIPTION
**Pull request by dscho**
This PR is not meant for merging, but for keeping track which parts of Scalar have made it upstream and which parts still need to be upstreamed (and which parts will remain in Microsoft's fork of Git).

The branch thicket in this PR essentially builds up Scalar on top of upstream's latest version, then reverts the Scalar patches out of `vfs-<version>`, merges the built-up Scalar, then applies the GVFS-protocol-specific parts on top.

My plan is to update the branch thicket whenever new iterations of the contributed patch series are available in https://github.com/gitster/git, in particular to ensure that the Scalar Functional Tests still pass.

### CODE REVIEW

**Comment by dscho** [comment]
Ah, that macOS flake in the Scalar Functional Tests [rears its head again](https://github.com/microsoft/git/runs/4949345550?check_suite_focus=true#step:16:3104)... Symptom:

```
1-1) Failed : Scalar.FunctionalTests.Tests.GitCommands.RebaseTests(SparseMode).RebaseDirectoryWithOneFileRead()
status Output Lines
status Output Lines counts do not match. was: 4 expected: 5
Extra: 'nothing to commit, working tree clean'
Missing: 'Changes to be committed:'
Missing: '	modified:   Readme.md'
Items ordered differently, found: 'nothing to commit, working tree clean' expected: 'Changes to be committed:'
   at Scalar.Tests.Should.EnumerableShouldExtensions.ShouldMatch[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, Boolean shouldMatchInOrder, String message) in /Users/runner/work/git/git/scalar/Scalar.TestInfrastructure/Should/EnumerableShouldExtensions.cs:line 163
   at Scalar.FunctionalTests.Tools.GitHelpers.LinesShouldMatch(String message, String expected, String actual) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 91
   at Scalar.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(ScalarFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 74
   at Scalar.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(ScalarFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 84
   at Scalar.FunctionalTests.Tests.GitCommands.GitRepoTests.ValidateFileDirectoryTest(String command, String commandBranch) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs:line 534
   at Scalar.FunctionalTests.Tests.GitCommands.GitRepoTests.RunFileDirectoryReadTest(String command, String commandBranch) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs:line 553
   at Scalar.FunctionalTests.Tests.GitCommands.RebaseTests.RebaseDirectoryWithOneFileRead() in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tests/GitCommands/RebaseTests.cs:line 110

1-2) Failed : Scalar.FunctionalTests.Tests.GitCommands.RebaseTests(SparseMode).RebaseDirectoryWithOneFileRead()
status Output Lines
status Output Lines counts do not match. was: 4 expected: 5
Extra: 'nothing to commit, working tree clean'
Missing: 'Changes to be committed:'
Missing: '	modified:   Readme.md'
Items ordered differently, found: 'nothing to commit, working tree clean' expected: 'Changes to be committed:'
   at Scalar.Tests.Should.EnumerableShouldExtensions.ShouldMatch[T](IEnumerable`1 group, IEnumerable`1 expectedValues, Func`3 equals, Boolean shouldMatchInOrder, String message) in /Users/runner/work/git/git/scalar/Scalar.TestInfrastructure/Should/EnumerableShouldExtensions.cs:line 163
   at Scalar.FunctionalTests.Tools.GitHelpers.LinesShouldMatch(String message, String expected, String actual) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 91
   at Scalar.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(ScalarFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 74
   at Scalar.FunctionalTests.Tools.GitHelpers.ValidateGitCommand(ScalarFunctionalTestEnlistment enlistment, ControlGitRepo controlGitRepo, String command, Object[] args) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tools/GitHelpers.cs:line 84
   at Scalar.FunctionalTests.Tests.GitCommands.GitRepoTests.TestValidationAndCleanup(Boolean ignoreCase) in /Users/runner/work/git/git/scalar/Scalar.FunctionalTests/Tests/GitCommands/GitRepoTests.cs:line 160
```

Preliminary analysis: This seems to be a flake, sometimes passing, sometimes not, and it seems dependent on how many tests are run concurrently, which makes me believe that it has _something_ to do with delivery of events (maybe there is an off-chance for the FSEvent machinery to reorder the events so that we see the sentinel event too early, or an mtime update not quite making it to the file system before the event is delivered...).

**Comment by dscho** [comment]
Hmm. Scalar's Functional Tests [fail](https://github.com/dscho/git/runs/6360332005?check_suite_focus=true#step:16:3079).

The reason is that it [expects the `.zip` file path to be shown](https://github.com/microsoft/scalar/blob/f513cd77991d8aef1c3f5ad1b4b5b9049f84c8de/Scalar.FunctionalTests/Tests/EnlistmentPerFixture/DiagnoseTests.cs#L29), which it is, but it expects it [on `stdout`](https://github.com/microsoft/scalar/blob/f513cd77991d8aef1c3f5ad1b4b5b9049f84c8de/Scalar.FunctionalTests/Tools/ScalarProcess.cs#L163-L175), but now we print it [to `stderr`](https://github.com/dscho/git/blob/0b7594fbd0803c99f210a1a1f82f80fad80b7446/scalar.c#L1237-L1240).

@derrickstolee what's your preferred way to handle this? I see three options (in order of my preference, most preferred first):

1. change Scalar's Functional Tests to stop verifying that the `.zip` file path is shown on `stdout`
2. change Scalar's Functional Tests to somehow include `stderr` when verifying that the `.zip` file path is displayed
3. add a patch to `vfs-with-scalar` to _also_ print the `.zip` file path to `stdout`; This patch would stay local to the Microsoft fork of Git

What do you think?

**Comment by dscho** [comment]
> what's your preferred way to handle this? I see three options (in order of my preference, most preferred first):
> 
>     1. change Scalar's Functional Tests to stop verifying that the `.zip` file path is shown on `stdout`
> 
>     2. change Scalar's Functional Tests to somehow include `stderr` when verifying that the `.zip` file path is displayed
> 
>     3. add a patch to `vfs-with-scalar` to _also_ print the `.zip` file path to `stdout`; This patch would stay local to the Microsoft fork of Git
> 
> 
> What do you think?

@derrickstolee I went with https://github.com/microsoft/git/pull/479/commits/48fa5767f26ce0aa5844e2f28d517696c4d75141 for now, but it's definitely not my favorite work-around.

**Comment by derrickstolee** [comment]
> > what's your preferred way to handle this? I see three options (in order of my preference, most preferred first):
> > ```
> > 1. change Scalar's Functional Tests to stop verifying that the `.zip` file path is shown on `stdout`
> > 
> > 2. change Scalar's Functional Tests to somehow include `stderr` when verifying that the `.zip` file path is displayed
> > 
> > 3. add a patch to `vfs-with-scalar` to _also_ print the `.zip` file path to `stdout`; This patch would stay local to the Microsoft fork of Git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think?
> 
> @derrickstolee I went with [48fa576](https://github.com/microsoft/git/commit/48fa5767f26ce0aa5844e2f28d517696c4d75141) for now, but it's definitely not my favorite work-around.

The right long-term thing to do is to update the Scalar Functional Tests to expect the new behavior from upstream. Having this short-term solution during the release window is fine. We can revert that commit between release cycles.

**Comment by dscho** [comment]
Whoa. That was from _the previous_ release window. I should have fixed that in the meantime, sorry.

@vdye maybe you can take care of adjusting `microsoft/scalar` to gracefully accept the messages both on `stdout` and `stderr`, and then drop this commit from the `vfs-with-scalar` branch?

**Comment by dscho** [comment]
Oh, and before I forget: I did integrate the current state in `tentative/vfs-2.37.0`. That should make it easier to adapt to more upstreamed bits and pieces in the future.

**Comment by dscho** [comment]
Now that all of the upstreamable parts of Scalar are upstreamed 🎉, this meta PR can be closed.

**Pull request closed without merging**
