### PR TITLE
[DO NOT MERGE] VFS4Git: Replace pre-V4 of FSMonitor with V4 candidate

### PR DESCRIPTION
**Pull request by jeffhostetler**
This is a trial merge of the new V4 version of FSMonitor directly into the VFS4Git version of Git.
I have rebased here the forest of commits from:  https://github.com/git-for-windows/git/pull/3447
for testing purposes.

Do not merge this.  microsoft/git should inherit these commits from GFW with the v2.34 update
rather than having a new copy.

### CODE REVIEW

**Comment by dscho** [comment]
There is a part of the range-diff between this PR and the Git for Windows one that worries me:

```diff
    @@ fsmonitor-settings.c (deleted)
     -
     -enum fsmonitor_mode fsm_settings__get_mode(struct repository *r)
     -{
    +-  if (git_config_get_virtualfilesystem())
    +-          return FSMONITOR_MODE_INCOMPATIBLE;
    +-
     -  if (!r->settings.fsmonitor)
     -          lookup_fsmonitor_settings(r);
     -
```

It means that this here PR removes a part of the `fsmonitor-settings.c` that I worry wasn't reinstated by mistake. At least I cannot find it anymore in this branch.

I would much rather merge the `try-v4-fsmonitor` branch directly. To that end, I rebased _that_ branch onto v2.33.0.windows.2, so that it can be merged with minimal fuss into `vfs-2.33.0`, too. (I guess we should merge v2.33.0.windows.2 first, though, in a separate PR...)

**Comment by jeffhostetler** [comment]
WRT the call to `git_config_get_virtualfilesystem()` I refactored the "incompatibility" checking code when I added the code to test for remote repos and created platform-specific implementations for some of the checks.  Now, `fsm_settings__get_mode()` calls thru several layers of static helpers and eventually ends up in compat/fsmonitor/fsm-settings-win32.c in `fsm_os__incompatible()` which has a simple `is_virtual()` helper.

Also, I have `is_virtual()` just use `repo_config_get_value()` rather than `git_config_get_virtualfilesystem()` to avoid the baggage and additional side-effects, so you're right, there is no matching destination for the original call.

Hopefully, I can get this simple helper function upstream.  If not, it is no big deal to carry it ourselves without conflicts.

**Comment by derrickstolee** [comment]
#436 is merged, so can we take the version from git-for-windows/git#3447?

**Comment by jeffhostetler** [comment]
Johannes made a note on one of these issues/PRs of taking the version of the GFW branch of mine that he updated to have "fixup!" commits rather than "revert" commits and then using those commits directly rather than the cherry-pick commits that I used in the microsoft/git branch.  So yes, we can update this branch to build on that.  I didn't want to try
do that while watching the Nova presentations.

When I did the cherry-pick there were a few merge conflicts because there were several GVFS changes that landed
near my FSMonitor changes in several places, so that make take a little tinkering.

**Comment by derrickstolee** [comment]
> Johannes made a note on one of these issues/PRs of taking the version of the GFW branch of mine that he updated to have "fixup!" commits rather than "revert" commits and then using those commits directly rather than the cherry-pick commits that I used in the microsoft/git branch. So yes, we can update this branch to build on that. I didn't want to try do that while watching the Nova presentations.
> 
> When I did the cherry-pick there were a few merge conflicts because there were several GVFS changes that landed near my FSMonitor changes in several places, so that make take a little tinkering.

In addition to having `fixup!` commits, it helps to use the exact commits from `git-for-windows/git` because they will be automatically dropped in the next `microsoft/git` rebase. Thanks for going through merge hell again.

**Comment by dscho** [comment]
> I didn't want to try
> do that while watching the Nova presentations.

Why not? 😇 

@jeffhostetler Couldn't we simply force-push the `try-v4-fsmonitor` branch as of e8f91a13a07c43e51e100ff3ae0440b2908e227a to `gvfs-try-v4-fsmonitor`? That _should_ work without merge conflicts (at least it did in my test a couple days ago).

**Comment by jeffhostetler** [comment]
I'm going to retire this one in favor of #437

**Pull request closed without merging**
