### PR TITLE
WIP [DO NOT MERGE] Test attempt to put existing FSMonitor code on top of multi-threaded simple-ipc code

### PR DESCRIPTION
**Pull request by jeffhostetler**
This PR moves the FSMonitor branch thicket onto the multi-threaded simple-ipc code.
A single fixup commit on top was added to switch to the multi-threaded IPC API.

FSMonitor builds and tests pass on both Windows and Mac, but I haven't actually made
any changes to the existing branch thicket.

This PR should replace #273.

TODO
[x] I hard-coded the number of threads in the call in FSMonitor to `ipc_server_run()`.  This should be a config setting or something.  -- I added `fsmonitor.ipcthreads` and `--ipcthreads`.

Depends on #281.

### CODE REVIEW

**Comment by jeffhostetler** [comment]
@dscho @derrickstolee  I pushed 4 TODO comments onto the end of this series with notes from my first pass at understanding the Windows version of FSMonitor.  (I was afraid of losing them from the PR experience if/when we do a thicket rebase or return to #273, so I put them inline directly.)

I didn't get thru the cookie and queue stuff yet.  I had to stop here. I'll dig into that on Monday.

**Comment by dscho** [comment]
Hah, I know what it is:

> Could not find /azure-pipelines.yml in repository

**Comment by jeffhostetler** [comment]
@dscho  I'm new to all of this /azp stuff.  so is the "/azp run microsoft.git" command wrong for this repo?  or is there something else causing the yellow dot on the "Microsoft.git Expected" step to never complete ???

**Comment by dscho** [comment]
>  I'm new to all of this /azp stuff. so is the "/azp run microsoft.git" command wrong for this repo? or is there something else causing the yellow dot on the "Microsoft.git Expected" step to never complete ???

The `/azp run microsoft.git` command relies on a definition (typically in `azure-pipelines.yml` _inside_ the worktree) to know what it should do.

But as of recently, there is no longer an `azure-pipelines.yml` in the worktree, we switched to using a GitHub workflow for that (we get double the concurrent agents that way).

The reason why the `Microsoft.git` job is mentioned _at all_ is that it is listed explicitly in the branch protection. If you go to https://github.com/microsoft/git/settings/branches, you will see this:

image

Clicking on the [`features/*` entry](https://github.com/microsoft/git/settings/branch_protection_rules/6196793), you will see this:

image

I think we simply have to "un-require" the `Microsoft.git` "status check". It no longer applies.

**Comment by jeffhostetler** [comment]
WOW!  Thanks for the info!

**Comment by derrickstolee** [comment]
I've removed the `microsoft.git` requirement, and added all the builds that actually ran on this PR, but why did others not run? 

**It's because you modified `.github/workflows/main.yml`.**

We'll want to re-add those steps as required into `features/*` again after this work is done.

**Comment by jeffhostetler** [comment]
Thanks!!!

Yes, I just noticed that one of the commits in the FSMonitor thicket turned off all non-fsmonitor tests.

**Comment by jeffhostetler** [comment]
Closing this obsolete FSMonitor PR in favor of #282.

**Pull request closed without merging**
