### PR TITLE
Create universal builds on macos

### PR DESCRIPTION
**Pull request by jeffhostetler**
Update config.mak.uname and GitHub workflow to create a DMG and PKG containing universal binaries rather than separate single-platform packages.

### CODE REVIEW

**Comment by jeffhostetler** [comment]
The compile/link in the macos build is failing because libcurl is not fat.  Homebrew does not ship universal binaries, but does ship skinny binaries for both platforms. We should look to add a step that takes them and lipo's them together before trying to compile git.

**Comment by dscho** [comment]
Update: I got things _mostly_ working in https://github.com/microsoft/git/tree/jh/macos-universal, but there's now a problem with docbook (seems that the `xmlcatalog` command has not run correctly, that should have updated the mappings so that no web request is made for those xsl files): https://github.com/microsoft/git/actions/runs/6734747576/job/18306328885#step:5:778. Got "side-tracked" by -rc0 release work.

**Comment by dscho** [comment]
> ```
> warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl"
> compilation error: file docbook.xsl line 3 element import
> xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl
> ```

I've seen similar problems before (in Git for Windows) when [the corresponding entry in `/etc/xml/catalog`](https://github.com/git-for-windows/git-sdk-64/blob/0d749022e34a463d9500c68734856d6000e5bcef/etc/xml/catalog#L9) was missing. These entries should be written by the `xmlcatalog` command, once the style sheets have been installed. I believe that [they should be installed correctly](https://github.com/microsoft/git/actions/runs/6734747576/workflow#L36) and then [this part](https://github.com/microsoft/git/actions/runs/6734747576/workflow#L87-L88) should ensure that they are used. But maybe something goes wrong [when `xmlcatalog` is run](https://github.com/microsoft/git/actions/runs/6734747576/job/18306328885#step:4:1822)?

**Comment by dscho** [comment]
> > ```
> > warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl"
> > compilation error: file docbook.xsl line 3 element import
> > xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl
> > ```
> 
> I've seen similar problems before (in Git for Windows) when [the corresponding entry in `/etc/xml/catalog`](https://github.com/git-for-windows/git-sdk-64/blob/0d749022e34a463d9500c68734856d6000e5bcef/etc/xml/catalog#L9) was missing. These entries should be written by the `xmlcatalog` command, once the style sheets have been installed. I believe that [they should be installed correctly](https://github.com/microsoft/git/actions/runs/6734747576/workflow#L36) and then [this part](https://github.com/microsoft/git/actions/runs/6734747576/workflow#L87-L88) should ensure that they are used. But maybe something goes wrong [when `xmlcatalog` is run](https://github.com/microsoft/git/actions/runs/6734747576/job/18306328885#step:4:1822)?

I fixed this via 757c884ebb48967f8228dc9fa9601da9f1136619: it was picking up the wrong flavor of Homebrew (`/usr/local/`) because we hard-coded that preference, and when I explicitly installed the Intel flavor of Homebrew on an ARM runner, well, things broke.

**Comment by dscho** [comment]
Update: I got things to build, but the validation of the installer is failing because it cannot find the `.pkg`. Here is the corresponding run: https://github.com/microsoft/git/actions/runs/6754709732#artifacts

**Comment by dscho** [comment]
> the validation of the installer is failing because it cannot find the `.pkg`

D'oh, it's still looking for `*x86_64*.pkg`, but the file name is `git-2.42.0.vfs.0.0-universal-universal.pkg`...

**Comment by dscho** [comment]
> > the validation of the installer is failing because it cannot find the `.pkg`
> 
> D'oh, it's still looking for `*x86_64*.pkg`, but the file name is `git-2.42.0.vfs.0.0-universal-universal.pkg`...

I managed to fix it (and while at it, extend the validation matrix to also test the result on macOS/ARM): https://github.com/microsoft/git/actions/runs/6759896633/job/18373034703

**Comment by dscho** [comment]
Okay, it works now (and I finally force-pushed a clean set of commits to this here PR). [This workflow](https://github.com/microsoft/git/actions/runs/6760074618) (which has only a couple of commits to reduce building to macOS) shows that it works, and that we're also nicely reducing the `.dmg` to a manageable size. @jeffhostetler could you please review?

**Comment by jeffhostetler** [comment]
Notes: testing the artifacts from https://github.com/microsoft/git/pull/612#issuecomment-1792549961 
* the dmg and pkg are named "git-2.42.0.vfs.0.0-universal-universal.pkg" -- we should drop one of those words, but that can wait until later.
* by dropping the duplicate dashed versions from the dmg/pkg, the size drops from 217MB to 47MB.

**Pull request merged**
